import { ImageResponse } from 'next/og'

export const runtime = 'edge'
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'
export const alt = 'Sprite sheet preview generated by AI Sprite Generator'

export default function Image({
  searchParams,
}: {
  searchParams: { sprite?: string }
}) {
  const sprite =
    searchParams.sprite ||
    'https://sprite-sheet-generator.com/dancing-frog.gif'

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: '#fff',
          fontSize: 48,
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={sprite}
          width={256}
          height={256}
          style={{ objectFit: 'contain' }}
          alt="Sprite preview"
        />
        <span style={{ marginTop: 40 }}>AI Sprite Generator</span>
      </div>
    ),
    {
      ...size,
    }
  )
}
